// 中2 Program 3・4 本文（2学期中間テスト範囲）。訳は学習用に作成したもの。
const PARTS=[
{id:"p3s",t:"Program 3 Scenes（p.32-33）",s:[
["Daniel","There is a festival this evening.","今夜お祭りがあるよ。"],
["Emily","Really! I want to go!","本当に！行きたい！"],
["Daniel","Let's play some games.","ゲームをしようよ。"],
["Emily","Oh, I can't wait!","ああ、待ちきれない！"],
["Daniel","Here's your poi.","はい、きみのポイだよ。"],
["Emily","How do I use it?","どうやって使うの？"],
["Daniel","You use it to scoop up fish.","魚をすくい上げるために使うんだよ。"],
["Emily","Really? It's too thin.","本当に？薄すぎるよ。"],
["Emily","I caught only one fish.","1匹しかつかまえられなかった。"],
["Daniel","Good job, Emily.","よくやったね、エミリー。"],
["Emily","Oh, I need a bowl to keep it in.","ああ、それを入れておくための入れ物が必要だ。"],
["Daniel","Just a small bowl is OK.","小さな入れ物で大丈夫だよ。"]],qa:[]},
{id:"p3-1",t:"Program 3 Part 1 お祭りの屋台料理（p.35）",s:[
["Daniel","Wow, there are so many food stands here.","わあ、ここにはとてもたくさんの屋台があるね。"],
["Mao","Yes. I want to eat an \"American dog.\"","うん。「アメリカンドッグ」が食べたいな。"],
["Daniel","An \"American dog\"? Ah, you mean a corn dog!","「アメリカンドッグ」？ああ、コーンドッグのことだね！"],
["Mao","A corn dog! I see.","コーンドッグ！なるほど。"],
["Mao","What do you want to have?","あなたは何を食べたい？"],
["Daniel","I want to have something sweet.","何か甘いものが食べたいな。"],
["Mao","How about wata-ame?","わたあめはどう？"],
["Daniel","Sounds good! It's cotton candy in English.","いいね！英語では cotton candy だよ。"],
["Daniel","It's from the U.S.","アメリカから来たものなんだ。"],
["Mao","Is it? I didn't know that.","そうなの？知らなかった。"]],
qa:[["What is an \"American dog\" in English?",["It's a corn dog.","It's cotton candy.","It's a hot dog.","It's sashimi."]],["Where is wata-ame from?",["It's from the U.S.","It's from Japan.","It's from the Netherlands.","It's from Canada."]]]},
{id:"p3-2",t:"Program 3 Part 2 アメリカの夏の風物詩（p.36）",s:[
["Mao","Do you have any food stands in the U.S.?","アメリカには屋台はある？"],
["Daniel","Well, we have lemonade stands in summer.","そうだね、夏にはレモネードスタンドがあるよ。"],
["Mao","Lemonade stands?","レモネードスタンド？"],
["Daniel","Yes. Children make lemonade by themselves.","うん。子どもたちが自分たちでレモネードを作るんだ。"],
["Daniel","Then they sell it to earn money.","それから、お金をかせぐためにそれを売るんだ。"],
["Mao","Did you make and sell it too?","あなたも作って売ったの？"],
["Daniel","Yes. I opened a lemonade stand in front of my house.","うん。家の前にレモネードスタンドを開いたよ。"],
["Mao","What did you buy with the money?","そのお金で何を買ったの？"],
["Daniel","I bought a basketball.","バスケットボールを買ったよ。"],
["Daniel","Can I make lemonade for you sometime soon?","近いうちにきみにレモネードを作ってもいい？"],
["Mao","Yes, please! I'm looking forward to it.","うん、お願い！楽しみにしているね。"]],
qa:[["Where did Daniel open his lemonade stand?",["In front of his house.","At the festival.","At school.","In the park."]],["Does Mao want to drink lemonade?",["Yes, she does.","No, she doesn't.","Yes, she did.","No, she isn't."]],["Why do children sell lemonade?",["To earn money.","To buy a bowl.","To eat sashimi.","To go hiking."]]]},
{id:"p3-3",t:"Program 3 Part 3 世界の屋台料理（p.37）",s:[
["Mao","Today, I'll talk about a traditional Dutch food.","今日は、伝統的なオランダの食べ物について話します。"],
["Mao","I have some pictures to show you.","みなさんに見せるための写真が何枚かあります。"],
["Mao","Look at these.","これらを見てください。"],
["Mao","This food looks like sashimi.","この食べ物はさしみのように見えます。"],
["Mao","Some people use toothpicks to eat it.","それを食べるのにつまようじを使う人もいます。"],
["Mao","Others enjoy it in \"the Dutch way.\"","「オランダ式」で楽しむ人もいます。"],
["Mao","You can buy it at food stands in the Netherlands.","オランダの屋台でそれを買うことができます。"],
["Mao","Around the world there are many kinds of street food to try.","世界中には、ためしてみるべきたくさんの種類の屋台料理があります。"],
["Mao","I think street food shows each country's food culture.","屋台料理はそれぞれの国の食文化を表していると思います。"]],
qa:[["Where can we buy the traditional Dutch food?",["At food stands in the Netherlands.","At a supermarket in Japan.","At a lemonade stand.","At a restaurant in Canada."]],["What does Mao think about street food?",["It shows each country's food culture.","It is too sweet.","It is very expensive.","It looks like a corn dog."]]]},
{id:"p3-a",t:"Program 3 Action（p.39）",s:[
["Ken","I want to sell something to eat.","何か食べるものを売りたいです。"],
["Ken","I think yakisoba is good.","焼きそばがいいと思います。"],
["Ken","Everyone loves its smell and taste.","みんなその香りと味が大好きです。"],
["Ken","On top of that, we can cook yakisoba easily.","それに加えて、焼きそばは簡単に作れます。"],
["Ken","I want to sell a lot to buy a present for Miki.","美希へのプレゼントを買うために、たくさん売りたいです。"]],qa:[]},
{id:"p4s",t:"Program 4 Scenes（p.52-53）",s:[
["Miki","What are you listening to?","何を聞いているの？"],
["Tom","Japanese enka.","日本の演歌だよ。"],
["Miki","Wow! I'm surprised to hear that.","わあ！それを聞いておどろいたよ。"],
["Tom","Actually, I'm a big fan of enka.","実は、ぼくは演歌の大ファンなんだ。"],
["Tom","This song is so emotional.","この歌はとても心にしみるんだ。"],
["Miki","You must turn down the volume.","音量を下げなきゃだめだよ。"],
["Miki","Uh-oh, you mustn't sing in the bus.","あらら、バスの中で歌ってはいけないよ。"],
["Tom","I have to be careful about the volume.","音量に気をつけなければいけないね。"],
["Tom","I'll cover my head with the hood.","フードで頭をおおうよ。"],
["Miki","You don't have to do that.","そうする必要はないよ。"]],qa:[]},
{id:"p4-1",t:"Program 4 Part 1 カナダでの新生活（p.55）",s:[
["Tom","Hi, Miki. How's it going?","やあ、美希。調子はどう？"],
["Miki","Fine, thanks.","元気だよ、ありがとう。"],
["Tom","I hear you like hiking. Is that true?","ハイキングが好きだと聞いたよ。本当？"],
["Miki","Yes. I often went hiking when I was in Japan.","うん。日本にいたとき、よくハイキングに行ったよ。"],
["Tom","I'm glad to hear that.","それを聞いてうれしいよ。"],
["Tom","Why don't we go hiking next Saturday?","今度の土曜日にハイキングに行かない？"],
["Tom","My uncle Eric will guide us.","おじのエリックが案内してくれるよ。"],
["Miki","That sounds wonderful. Where will we meet?","すばらしいね。どこで会う？"],
["Tom","Can you come to my house at six in the morning?","朝6時にぼくの家に来られる？"],
["Miki","Sure. I hope it'll be clear on that day.","もちろん。その日は晴れるといいな。"]],
qa:[["What will Miki do next Saturday?",["She will go hiking.","She will go to a festival.","She will sell lemonade.","She will go to Japan."]],["Who will guide Tom and Miki?",["Eric, Tom's uncle, will.","Miki's father will.","Daniel will.","Mao will."]],["What time will they meet?",["At six in the morning.","At six in the evening.","At nine in the morning.","At noon."]]]},
{id:"p4-2",t:"Program 4 Part 2 バンフ国立公園に来た！（p.56）",s:[
["Miki","What a breathtaking place!","なんて息をのむような場所なんだろう！"],
["Miki","I'm so excited to be here.","ここにいられてとてもわくわくしているよ。"],
["Eric","Wait. First of all, let's check the hiking rules.","待って。まず最初に、ハイキングのルールを確認しよう。"],
["Miki","\"Take only pictures, leave only footprints.\" Right?","「写真だけを撮り、足あとだけを残せ」ですよね？"],
["Eric","Yes. We can take pictures, but we must not take anything from the forest.","そうだね。写真は撮ってもいいけれど、森から何も持って行ってはいけないよ。"],
["Tom","And we must bring our garbage back home.","それに、ごみは家に持ち帰らなければならないね。"],
["Miki","Yeah. We must protect nature.","うん。自然を守らなければいけないね。"],
["Eric","Now, let's go. If you have any trouble, tell me.","さあ、行こう。何か困ったことがあったら、ぼくに言ってね。"]],
qa:[["What does \"leave only footprints\" mean?",["Don't leave anything in nature.","Take a lot of things home.","Walk without shoes.","Draw pictures of footprints."]],["Can they take pictures in the forest?",["Yes, they can.","No, they can't.","Yes, they must.","No, they don't have to."]],["What must they bring back home?",["Their garbage.","Some flowers.","A beaver.","Some stones."]]]},
{id:"p4-3",t:"Program 4 Part 3 木が倒されている！（p.57）",s:[
["Miki","How terrible! Who cut down this tree?","なんてひどい！だれがこの木を切り倒したの？"],
["Tom","You don't have to worry. I think a beaver did it.","心配する必要はないよ。ビーバーがやったんだと思う。"],
["Miki","You know a lot about beavers?","ビーバーについてよく知っているの？"],
["Tom","Yes. They're one of Canada's national animals.","うん。ビーバーはカナダの国獣の1つなんだ。"],
["Miki","Are they? They build dams and lodges, right?","そうなの？ダムや巣を作るんだよね？"],
["Tom","Exactly. They're great engineers.","そのとおり。すごい技術者なんだ。"],
["Miki","Do you think we'll see any beavers today?","今日ビーバーを見られると思う？"],
["Tom","I don't think so. They sleep in their lodges during the day.","そうは思わないな。昼間は巣の中で眠っているんだ。"],
["Miki","Then we have to be quiet.","それなら静かにしなければいけないね。"]],
qa:[["What do beavers build?",["They build dams and lodges.","They build houses for people.","They build lemonade stands.","They build bridges for cars."]],["Will Miki and Tom see beavers today?",["Probably not. Beavers sleep during the day.","Yes. Beavers are awake during the day.","Yes. They will see many beavers.","No. Beavers don't live in Canada."]]]},
{id:"p4-a",t:"Program 4 Action 修学旅行のルール（p.59）",s:[
["Anya","We must be on time.","私たちは時間を守らなければなりません。"],
["Anya","We must not make loud noises on the train.","電車の中で大きな音を立ててはいけません。"],
["Anya","We can bring some snacks.","おやつを持ってきてもよいです。"],
["Anya","We don't have to bring our own shampoo.","自分のシャンプーを持ってくる必要はありません。"]],qa:[]}
];
